### ISSUE TITLE
Initial documentation checklist

### ISSUE THREAD

**Issue by AidanTilgner** [VVibrant-Web-Solutions/Onyx-Chat-Documentation#1]
We need an initial draft of the documentation which can get a user from 0 to getting a chatbot on their website. This will be initially targeted as developers, as in there will be extra detail. The things to cover are:

- [ ] Get a user from 0 to their first bot
- [ ] Get a user from a standard bot to a more advanced bot, going through each of the workflows
- [ ] Get a user to be able to work with their bot through the API
- [ ] Get a user to be able to manage an organization

**Comment by AidanTilgner** [comment]
I've decided to go with a new approach to documentation. I'm opening a new issue [here](https://github.com/VVibrant-Web-Solutions/Onyx-Chat-Documentation/issues/2).
